version: '3'

services:
  getaway:
    container_name: getaway
    restart: always
    build: ./getaway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "8001:8000"

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - "8002:8000"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - "8003:8000"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "8004:8000"
